theme: jekyll-theme-modernist
title: "Towards a better prediction of civil wars - Correcting an imbalanced dataset"
description: "This website displays the results of team GYC's project for the ADA course during the autumn semester of 2020"