theme: jekyll-theme-modernist
title: "Civil War Dataset : Binary Classification Performance Evaluation with Data Correction"
description: "This website displays the results of team GYC's project for the ADA course during the autumn semester of 2020"